Ejercicios de ficheros

In [1]:
import numpy as np

In [21]:
my_list = list(range(10)) # Utilizando Listas Python
my_list = [x * 2 for x in my_list]
my_list

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
my_arr = np.arange(10) # Utilizando NumPy Arrays
my_arr= my_arr * 2
print (my_arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
array = np.array([ [2,71,0,34], [2,171,-35,34] ]) # 2D
print(array)

[[  2  71   0  34]
 [  2 171 -35  34]]


In [18]:
v= np.array([[21,12,312, 30], [10,12,123, 21], [21,4,56, 10]])

print(v)

[[ 21  12 312  30]
 [ 10  12 123  21]
 [ 21   4  56  10]]


In [20]:
shopping_list = [ ['onions', 'carrots', 'celery'], ['apples', 'oranges','grapes'] ] # 2D
array = np.array(shopping_list) # convertir una lista en una ndarray
print(array)
print(type(array))

[['onions', 'carrots', 'celery'], ['apples', 'oranges', 'grapes']]
[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


In [23]:
print(np.array([100,10,1])) # array a partir de una lista
print(np.arange(2,10,2.1)) # array a partir de una secuencia(range) 1D

[100  10   1]
[2.  4.1 6.2 8.3]


In [39]:
print(np.empty((2,2,2)))

[[[9.88e-324 3.51e-322]
  [0.00e+000 1.68e-322]]

 [[9.88e-324 8.45e-322]
  [      nan 1.68e-322]]]


In [3]:
arr = np.empty((3,3))

for i in range(3):
    for j in range(3):
        arr[i,j] = i*j

print(arr)

[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]


In [15]:
## 2. Print the numpy version and the configuration (★☆☆)

print(np.__version__)
np.show_config()

2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: E:/anaconda/Library/include
    lib directory: E:/anaconda/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: E:/anaconda/Library/include
    lib directory: E:/anaconda/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.4
Machine Information:
  build:
    cpu

In [24]:
## How to find the memory size of any array

neArray= np.array([[2,3,4], [3,5,7]])
print (neArray.nbytes)

48


In [32]:
## Create a null vector of size 10 but the fifth value which is 1
newA= np.zeros(10)
newA[4]=1
print(newA)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [36]:
## Reverse a vector (first element becomes last)
newAr= np.arange(10)

alrevez=newAr[::-1]

print(alrevez)

[9 8 7 6 5 4 3 2 1 0]


In [7]:
## Find indices of non-zero elements from [1,2,0,0,4,0]
lista=[1,2,0,0,4,0]

listan=[]

for x in range(len(lista)):
    if lista[x] != 0:
        listan.append(x)

print (listan)

[0, 1, 4]


In [ ]:
# Lectura desde fichero usando método 'read'. Devuelve todo el contenido del fichero.
mi_fichero = open('res/multiple_lines.txt')
print(mi_fichero.read())
1
mi_fichero.close()